# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 23:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=50)),
                ('tariff', models.DecimalField(decimal_places=2, max_digits=8)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.City')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.Host')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 10, 26, 23, 4, 43, 251000, tzinfo=utc))),
                ('guest', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.Property')),
            ],
        ),
        migrations.AddField(
            model_name='availableday',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.Property'),
        ),
        migrations.AddField(
            model_name='availableday',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Reservation'),
        ),
    ]
