# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 21, 8, 49, 160000, tzinfo=utc)),
        ),
    ]
