# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 07:47
from __future__ import unicode_literals

import datetime
import django.core.files.storage
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_auto_20181106_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=b'C:/static/images'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 7, 47, 27, 273000, tzinfo=utc)),
        ),
    ]
