# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 23:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_auto_20181107_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 23, 52, 21, 411000, tzinfo=utc)),
        ),
    ]
